### ISSUE TITLE
Update Dockerfile to utilize Wattile 0.3.0 release

### ISSUE THREAD

**Issue by smithcommajoseph** [NREL/nrelWattileExt#75]

**Comment by stephen-frank** [comment]
The build works but there is an error using the resulting 0.3.0 image from SkySpark:

```
axon::EvalErr: Func failed: pyEval(PySession py,Str stmt); args: (PyMgrSession,Str)
  sys::IOErr: Python failed: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/site-packages/pyproject.toml'
Traceback (most recent call last):
  File "/usr/src/app/hxpy/hxpy.py", line 67, in run
    self._exec(instr, local_vars)
  File "/usr/src/app/hxpy/hxpy.py", line 95, in _exec
    return exec(code, local_vars, local_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/wattile/__init__.py", line 8, in <module>
    with open(proj_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.12/site-packages/pyproject.toml'
[nrelWattile::wattilePythonModelPredict:91]
```

It seems to originate in Wattile's `__init__.py` and is preventing anything Wattile-related from executing.

**Comment by stephen-frank** [comment]
The good news is the bit where we put hxpy into Python 3.12 _seems_ to work properly:

```
py({image:"wattile_0.3.0"}).pyDefine("x", 1).pyExec("x = x + x").pyEval("x")  >> 2
```

**Comment by stephen-frank** [comment]
Complete with #76
